### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by lander1003** [qingsenyangit/AHDRNet#17]
Have you ever met the problem that CUDA out of memory? I have two gpus and both is Tesla T4 16g, even I set the batchsize to 1 ,the problem still happens. Follow is the error code:
Traceback (most recent call last):
  File "script_testing.py", line 63, in <module>
    loss = testing_fun(model, testimage_dataset, args)
  File "/root/AHDRNet/running_func.py", line 185, in testing_fun
    output = model.forward(data1, data2, data3)
  File "/root/miniconda2/envs/hdr/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 152, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/root/miniconda2/envs/hdr/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 162, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/root/miniconda2/envs/hdr/lib/python2.7/site-packages/torch/nn/parallel/parallel_apply.py", line 83, in parallel_apply
    raise output
RuntimeError: CUDA out of memory. Tried to allocate 2.86 GiB (GPU 0; 14.76 GiB total capacity; 13.19 GiB already allocated; 873.75 MiB free; 11.17 MiB cached)
 Thank you

**Comment by lander1003** [comment]
and if I use cpu , it will be killed

**Comment by hangxiaotian** [comment]
> Have you ever met the problem that CUDA out of memory? I have two gpus and both is Tesla T4 16g, even I set the batchsize to 1 ,the problem still happens. Follow is the error code: Traceback (most recent call last): File "script_testing.py", line 63, in loss = testing_fun(model, testimage_dataset, args) File "/root/AHDRNet/running_func.py", line 185, in testing_fun output = model.forward(data1, data2, data3) File "/root/miniconda2/envs/hdr/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 152, in forward outputs = self.parallel_apply(replicas, inputs, kwargs) File "/root/miniconda2/envs/hdr/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 162, in parallel_apply return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)]) File "/root/miniconda2/envs/hdr/lib/python2.7/site-packages/torch/nn/parallel/parallel_apply.py", line 83, in parallel_apply raise output RuntimeError: CUDA out of memory. Tried to allocate 2.86 GiB (GPU 0; 14.76 GiB total capacity; 13.19 GiB already allocated; 873.75 MiB free; 11.17 MiB cached) Thank you

I think you can add the following code:
if torch.cuda.device_count() > 1:
     model = nn.DataParallel(model)

**Comment by YounZh** [comment]
> Have you ever met the problem that CUDA out of memory? I have two gpus and both is Tesla T4 16g, even I set the batchsize to 1 ,the problem still happens. Follow is the error code: Traceback (most recent call last): File "script_testing.py", line 63, in loss = testing_fun(model, testimage_dataset, args) File "/root/AHDRNet/running_func.py", line 185, in testing_fun output = model.forward(data1, data2, data3) File "/root/miniconda2/envs/hdr/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 152, in forward outputs = self.parallel_apply(replicas, inputs, kwargs) File "/root/miniconda2/envs/hdr/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 162, in parallel_apply return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)]) File "/root/miniconda2/envs/hdr/lib/python2.7/site-packages/torch/nn/parallel/parallel_apply.py", line 83, in parallel_apply raise output RuntimeError: CUDA out of memory. Tried to allocate 2.86 GiB (GPU 0; 14.76 GiB total capacity; 13.19 GiB already allocated; 873.75 MiB free; 11.17 MiB cached) Thank you

Add "with torch.no_grad():" when testing.
